### ISSUE TITLE
Values not sent to heatpump / thermIQ causing alert state

### ISSUE THREAD

**Issue by ioT-enthusiast** [ThermIQ/thermiq_mqtt-ha#37]
Hi Anders,

I am having problems with my Thermiq-MQTT device and/or the Integration.

Values are received and shown correctly in HA (and visible in MQTT Explorer). But I am not able to change them. Not even target temperature. After changing the old value returns after seconds. In MQTT explorer I dont see any write Message from HA in the topic, so I assume the changed value is not transmitted.

I added “hexformat: True” to configuration Yaml, but no changes. Even resetted the device and changed the Mqtt Topic to standard “ThermIQ/ThermÍQ-mqtt” (in the device and in the HA config). No changes.

Firmware is 1.4.2. I tried firmware update through the device menu, but it only shows a handful of TLS/SSL Handshake error messages. Is 1.4.2 the actual and newest 1.x firmware?

Another error accurs: after about 2 days the heatpump (Thermia Comfort Optimum from 2015) is giving alarm. The internal alarm-board is plugged in after the ThermIQ (even tried to not connect the alarm board, same story). No other boards connected. WIthout ThermIQ-MQTT connected the heatpump runs without any problems.

Can you pls take a look at this?

**Comment by ThermIQ** [comment]
The first problem is likely something with your HA setup, please check your config and log-files.

You are on the latest fw for 1.xx and there is unfortunately no upgrade path to fw 2.xx available.

The fw 1.xx requires hexformat: True in order to work properly, mqtt messages will be sent regardless of this but not interpreted correctly by ThermIQ-mqtt

The MQTT Topic is freely configrable, just make sure you set it to the same both in config and in the card.

Finally, your intermittent Alarm signal will most likely go away if you disconnect the thin red cable between ThermIQ-mqtt and the heatpump interface.

**Comment by ThermIQ** [comment]
Any update if cutting red wire resolved the communication issue?
